sudo: required
language: C++
addons:
  apt:
    packages: cmake ninja-build
before_install:
        - mkdir build
        - cd build
        - cmake .. -G Ninja
install:
        - ninja && sudo ninja install
script:
        - ls /usr/lib/libInexactAdders.a
        - ls /usr/include/inexact_adders.h
