sudo: required
language: CXX
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y cmake ninja-build
        - mkdir build
        - cd build
        - cmake .. -G Ninja
install:
        - ninja && sudo ninja install
script:
        - ls /usr/lib/libInexactAdders.a
        - ls /usr/include/inexact_adders.h
